version: '3.8'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: 'npm-h'
    container_name: 'npm-c'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - '$APP_DCHOMEDIR/npm-pdata/letsencrypt:/etc/letsencrypt'
      - '$APP_DC_HOMEDIR/npm-pdata/npm/data:/data'

  npm-db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    hostname: 'npm-db-h'
    container_name: 'npm-db-c'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - '$APP_DC_HOMEDIR/npm-pdata/npm-db/mysql:/var/lib/mysql'